GET http://localhost:3000



/* authenticate with passport and session
app.use(session({
    name : 'session-id',
    secret : '12345-67890-09876-54321',
    saveUninitialized : false,
    resave :false,
}))
app.use(passport.session());


app.use((req, res , next) => {
    if (!req.user) {
        var err  = new Error('you are not athenticated') ;
        err.status = 403;
        next('err');
    }else {
        next();
    } 
})

// athenticate with express-session
app.use((req, res , next) => {
    if (!req.session.user) {
        var err  = new Error('you are not athenticated') ;
        err.status = 403;
        next('err');
    }else {
        if (req.session.user === 'authenticated') {
            next()
        }else {
            var err = new Error('you are not ethenticated');
            err.status = 403;
            next(err);
        }
    } 
})

// authentification with basic authentification && cookies
app.use((req, res, next) =>{
        if (!req.signedCookies.user) {
            
        var authHeader = req.headers.authorization;
        if (!authHeader) {
            var err = new Error('You are not authenticated!');
            res.setHeader('WWW-Authenticate', 'Basic');
            err.status = 401;
            next(err);
            return;
        }
      
        var auth = new Buffer.from(authHeader.split(' ')[1], 'base64').toString().split(':');
        var user = auth[0];
        var pass = auth[1];
        if (user == 'admin' && pass == 'password') {
            res.cookie('user','admin',{signed : true});
            next(); // authorized
        } else {
            var err = new Error('You are not authenticated!');
            res.setHeader('WWW-Authenticate', 'Basic');      
            err.status = 401;
            next(err);
        }      
    }else if (req.signedCookies.user === 'admin') {
        next()
    }else {
        var err = new Error('You are not atheniticated');
        err.status = 401;
        next(err)
    }
   
  })
  */